package movienight.model;

public class Attendances {
	
	protected int attendanceId;
	protected MovieNights movieNight;
	protected Users user;
	protected AttendanceType attendanceType;
	
	public enum AttendanceType {
		host, attendee
	}
	
	public Attendances(int attendanceId, MovieNights movieNight, Users user, AttendanceType attendanceType) {
		this.attendanceId = attendanceId;
		this.movieNight = movieNight;
		this.user = user;
		this.attendanceType = attendanceType;
	}
	
	// This constructor can be used for creating new records, where the attendanceId may not be
	// assigned yet since it is auto-generated by MySQL.
	public Attendances(MovieNights movieNight, Users user, AttendanceType attendanceType) {
		this.movieNight = movieNight;
		this.user = user;
		this.attendanceType = attendanceType;
	}
	
	public Attendances(int attendanceId) {
		this.attendanceId = attendanceId;
	}
	
	/** Getters and setters. */
	
	public int getAttendanceId() {
		return attendanceId;
	}

	public void setAttendanceId(int attendanceId) {
		this.attendanceId = attendanceId;
	}

	public MovieNights getMovieNight() {
		return movieNight;
	}

	public void setMovieNight(MovieNights movieNight) {
		this.movieNight = movieNight;
	}

	public Users getUser() {
		return user;
	}

	public void setUserName(Users user) {
		this.user = user;
	}

	public AttendanceType getAttendanceType() {
		return attendanceType;
	}

	public void setAttendanceType(AttendanceType attendanceType) {
		this.attendanceType = attendanceType;
	}

}
