package movienight.model;

public class LikePersons {
	protected int likePersonId;
	protected Persons person;
	protected Users user;
	
	public LikePersons(int likePersonId, Persons person, Users user) {
		this.likePersonId = likePersonId;
		this.person = person;
		this.user = user;
	}
	
	// This constructor can be used for creating new records, where wishListMovieId may not be
	// assigned yet since it is auto-generated by MySQL.
	public LikePersons(Persons person, Users user) {
		this.person = person;
		this.user = user;
	}
	
	public LikePersons(int likePersonId) {
		this.likePersonId = likePersonId;
	}
	
	/** Getters and setters. */

	public int getLikePersonId() {
		return likePersonId;
	}

	public void setLikePersonId(int likePersonId) {
		this.likePersonId = likePersonId;
	}

	public Persons getPerson() {
		return person;
	}

	public void setPerson(Persons person) {
		this.person = person;
	}

	public Users getUser() {
		return user;
	}

	public void setUser(Users user) {
		this.user = user;
	}

}
