package movienight.model;

public class LikePersons {
	protected int likePersonId;
	protected int personId;
	protected Users userName;
	
	public LikePersons(int likePersonId, int personId, Users userName) {
		this.likePersonId = likePersonId;
		this.personId = personId;
		this.userName = userName;
	}
	
	// This constructor can be used for creating new records, where wishListMovieId may not be
	// assigned yet since it is auto-generated by MySQL.
	public LikePersons(int personId, Users userName) {
		this.personId = personId;
		this.userName = userName;
	}
	
	public LikePersons(int likePersonId) {
		this.likePersonId = likePersonId;
	}
	
	/** Getters and setters. */

	public int getLikePersonId() {
		return likePersonId;
	}

	public void setLikePersonId(int likePersonId) {
		this.likePersonId = likePersonId;
	}

	public int getPersonId() {
		return personId;
	}

	public void setPersonId(int personId) {
		this.personId = personId;
	}

	public Users getUserName() {
		return userName;
	}

	public void setUserName(Users userName) {
		this.userName = userName;
	}

}
