package movienight.model;

import java.util.Date;

public class Reviews {
	protected int reviewId;
	protected Date created;
	protected String content;
	protected double rating;
	protected Users user;
	protected Movies movie;
	
	public Reviews(int reviewId, Date created, String content, double rating, Users user, Movies movie) {
		this.reviewId = reviewId;
		this.created = created;
		this.content = content;
		this.rating = rating;
		this.user = user;
		this.movie = movie;
	}
	
	// This constructor can be used for creating new records, where reviewId & created may not be
	// assigned yet since it is auto-generated by MySQL.
	public Reviews(String content, double rating, Users user, Movies movie) {
		this.content = content;
		this.rating = rating;
		this.user = user;
		this.movie = movie;
	}
	
	public Reviews(int reviewId) {
		this.reviewId = reviewId;
	}
	
	
	/** Getters and setters. */
	
	public int getReviewId() {
		return reviewId;
	}

	public void setReviewId(int reviewId) {
		this.reviewId = reviewId;
	}

	public Date getCreated() {
		return created;
	}

	public void setCreated(Date created) {
		this.created = created;
	}

	public String getContent() {
		return content;
	}

	public void setContent(String content) {
		this.content = content;
	}

	public double getRating() {
		return rating;
	}

	public void setRating(double rating) {
		this.rating = rating;
	}

	public Users getUser() {
		return user;
	}

	public void setUser(Users user) {
		this.user = user;
	}

	public Movies getMovie() {
		return movie;
	}

	public void setMovie(Movies movie) {
		this.movie = movie;
	}

}
