package movienight.model;

public class WatchedMovies {
	
	protected int watchedMovieId;
	protected Movies movie;
	protected Users user;
	
	public WatchedMovies(int watchedMovieId, Movies movie, Users user) {
		this.watchedMovieId = watchedMovieId;
		this.movie = movie;
		this.user = user;
	}
	
	// This constructor can be used for creating new records, where watchedMovieId may not be
	// assigned yet since it is auto-generated by MySQL.
	public WatchedMovies(Movies movie, Users user) {
		this.movie = movie;
		this.user = user;
	}
	
	public WatchedMovies(int watchedMovieId) {
		this.watchedMovieId = watchedMovieId;
	}
	
	/** Getters and setters. */
	
	public int getWatchedMovieId() {
		return watchedMovieId;
	}

	public void setWatchedMovieId(int watchedMovieId) {
		this.watchedMovieId = watchedMovieId;
	}

	public Movies getMovie() {
		return movie;
	}

	public void setMovie(Movies movie) {
		this.movie = movie;
	}

	public Users getUser() {
		return user;
	}

	public void setUser(Users user) {
		this.user = user;
	}
}

