package movienight.model;

public class WishListMovies {
	protected int wishListMovieId;
	protected Movies movie;
	protected Users user;
	
	public WishListMovies(int wishListMovieId, Movies movie, Users user) {
		this.wishListMovieId = wishListMovieId;
		this.movie = movie;
		this.user = user;
	}
	
	// This constructor can be used for creating new records, where wishListMovieId may not be
	// assigned yet since it is auto-generated by MySQL.
	public WishListMovies(Movies movie, Users user) {
		this.movie = movie;
		this.user = user;
	}
	
	public WishListMovies(int wishListMovieId) {
		this.wishListMovieId = wishListMovieId;
	}
	
	
	/** Getters and setters. */
	
	public int getWishListMovieId() {
		return wishListMovieId;
	}

	public void setWishListMovieId(int wishListMovieId) {
		this.wishListMovieId = wishListMovieId;
	}

	public Movies getMovie() {
		return movie;
	}

	public void setMovie(Movies movie) {
		this.movie = movie;
	}

	public Users getUser() {
		return user;
	}

	public void setUser(Users user) {
		this.user = user;
	}

}

